[package]
name = "demo"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]
httpz = { path = "../../../../../", features = ["lambda"] }
tokio = "1.33.0"
lambda_http = "0.8.1"
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
